### ISSUE TITLE
Game cannot be launched due to missing image

### ISSUE THREAD

**Issue by Grimmys** [FestyWalrus/Water-Wall#1]
Hey,

Here is what I get if I try to execute waterwall.py :

`Traceback (most recent call last):
  File "waterwall.py", line 2, in <module>
    import gameparts
  File "C:\Users\Grimmys\Desktop\Water-Wall-master\gameparts.py", line 6, in <module>
    titleImg = pygame.image.load('data/images/title.png')
pygame.error: Couldn't open data/images/title.png
`

**Comment by RKnybel** [comment]
Aha, I forgot to upload some images. If you download the game again, it should run properly. Thank you!

**Comment by Grimmys** [comment]
Yes it works now. ;)
