### ISSUE TITLE
Add option to move block in different positions

### ISSUE THREAD

**Issue by molecula451** [FestyWalrus/Water-Wall#3]
As title says. Option to move blocks in different positions would improve t he gameability

**Comment by RKnybel** [comment]
What does this mean? The blocks can already rotate and move left or right

**Comment by molecula451** [comment]
Alright, yes! I got the keystrokes. We would need instead to add in the visual for improvement so a possible user may see what keys exactly are.

**Comment by molecula451** [comment]
@FestyWalrus You may be wondering. What exactly impulse me to contribute to the project. Well I was laying out and I got tired on excessive load on PHP old tetris and consuming unnecesary internet bandwidth. Further. I was kinda inspired quite ago and decided to take the snake by the throat and have fun with it on a Tetris. Found yours. :)

**Comment by RKnybel** [comment]
Thank you c: and did you mean a help screen? I'm still not really understanding what you mean.
